/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

 plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("application")
    id("java")
    // optionally sets project version and seelcts Java toolchain to use
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

tasks.named<Test>("test") {
	useJUnitPlatform()
	testLogging {
		events("passed", "skipped", "failed")
	}
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

// application {
//     // Define the main class for the application.
//     mainClass = "org.example.App"
// }
